# Modelação {#modeling}

```{r}
red_wine$is_good <- red_wine$quality >= 6
  
white_wine$is_good <- white_wine$quality >= 7
#white_wine$is_good <- ifelse(white_wine$quality > 5, 1, 0)
```

```{r}
table(white_wine$is_good)
nrow(white_wine)
table(red_wine$is_good)
```

```{r}

folds <- cut(seq(1, nrow(red_wine)), breaks = 10, labels = FALSE)

for (i in 1:10) {
  test.indexes <- which(folds == i, arr.ind = TRUE)
  red_wine.test <- red_wine[test.indexes, ]
  red_wine.train <- red_wine[-test.indexes, ]
}

glm.fit=glm(red_wine$is_good ~ ., data=red_wine, family=binomial)
summary(glm.fit)
coef(glm.fit)
summary(glm.fit)$coef

glm.probs=predict(glm.fit, type="response")
glm.pred=rep("Bad", nrow(red_wine))
glm.pred[glm.probs>.5]="Good"
table(glm.pred, red_wine$is_good)
```

```{r}
glm.fit=glm(red_wine$is_good ~ alcohol + citric.acid + fixed.acidity + volatile.acidity + sulphates, data=red_wine, family=binomial)
summary(glm.fit)
coef(glm.fit)
summary(glm.fit)$coef

glm.probs=predict(glm.fit, type="response")
red_wine_size <- length(red_wine$quality)

glm.pred=rep("Bad", red_wine_size)

glm.pred[glm.probs>.5]="Good"

table(glm.pred, red_wine$is_good)
```

